import type { AxeItem } from "../../../types";

export const AXES:AxeItem[] = [
  {id:"bronze-axe",name:"Bronze Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:1,value:16,bonusChance:0,description:"A dependable first axe",metal:"#a76b3f",edge:"#d19a62",handle:"#6e462a",shape:0},
  {id:"iron-hatchet",name:"Iron Hatchet",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:5,value:56,bonusChance:.05,description:"5% chance to cut an extra log",metal:"#70756f",edge:"#aeb2a8",handle:"#664329",shape:1},
  {id:"steel-feller",name:"Steel Feller",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:10,value:200,bonusChance:.10,description:"10% chance to cut an extra log",metal:"#6e7d82",edge:"#c6d0cc",handle:"#70472c",shape:2},
  {id:"ashen-splitter",name:"Ashen Splitter",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:15,value:500,bonusChance:.15,description:"15% chance to cut an extra log",metal:"#5e5b59",edge:"#aaa39b",handle:"#3f332a",shape:3},
  {id:"silverleaf-axe",name:"Silverleaf Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:20,value:900,bonusChance:.20,description:"20% chance to cut an extra log",metal:"#81948b",edge:"#d4e3d9",handle:"#71523b",shape:4},
  {id:"deepforge-axe",name:"Deepforge Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:25,value:1500,bonusChance:.25,description:"25% chance to cut an extra log",metal:"#4f5960",edge:"#a7b4b9",handle:"#45352b",shape:0},
  {id:"briar-edge",name:"Briar Edge",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:30,value:2500,bonusChance:.30,description:"30% chance to cut an extra log",metal:"#496447",edge:"#8da66f",handle:"#58402c",shape:1},
  {id:"emberbite",name:"Emberbite",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:35,value:4000,bonusChance:.35,description:"35% chance to cut an extra log",metal:"#8a3f2c",edge:"#e28445",handle:"#522f25",shape:2},
  {id:"frostcleaver",name:"Frostcleaver",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:40,value:6500,bonusChance:.40,description:"40% chance to cut an extra log",metal:"#65919c",edge:"#c0e4e5",handle:"#4d4b46",shape:3},
  {id:"storm-hew",name:"Storm Hew",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:45,value:9000,bonusChance:.45,description:"45% chance to cut an extra log",metal:"#4e5d79",edge:"#9eafd0",handle:"#4c392c",shape:4},
  {id:"moonsteel-axe",name:"Moonsteel Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:50,value:13000,bonusChance:.50,description:"50% chance to cut an extra log",metal:"#77758c",edge:"#d1cfe8",handle:"#55496b",shape:0},
  {id:"sunforged-axe",name:"Sunforged Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:55,value:18000,bonusChance:.55,description:"55% chance to cut an extra log",metal:"#a96d2b",edge:"#f0c05e",handle:"#6b3e27",shape:1},
  {id:"runebark-cutter",name:"Runebark Cutter",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:60,value:25000,bonusChance:.60,description:"60% chance to cut an extra log",metal:"#426c61",edge:"#70baa3",handle:"#3e5339",shape:2},
  {id:"obsidian-beak",name:"Obsidian Beak",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:65,value:35000,bonusChance:.65,description:"65% chance to cut an extra log",metal:"#292a34",edge:"#796c8f",handle:"#3d2d35",shape:3},
  {id:"dragonbone-axe",name:"Dragonbone Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:70,value:50000,bonusChance:.70,description:"70% chance to cut an extra log",metal:"#89634d",edge:"#d9c49d",handle:"#5a3029",shape:4},
  {id:"spiritwood-crescent",name:"Spiritwood Crescent",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:75,value:70000,bonusChance:.75,description:"75% chance to cut an extra log",metal:"#3e746a",edge:"#8bd4bd",handle:"#4d6545",shape:0},
  {id:"starfall-axe",name:"Starfall Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:80,value:100000,bonusChance:.80,description:"80% chance to cut an extra log",metal:"#536b8a",edge:"#b8d1e8",handle:"#463c5d",shape:1},
  {id:"voidglass-axe",name:"Voidglass Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:85,value:150000,bonusChance:.85,description:"85% chance to cut an extra log",metal:"#352b4c",edge:"#a174c4",handle:"#292233",shape:2},
  {id:"elder-king-axe",name:"Elder King's Axe",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:90,value:250000,bonusChance:.90,description:"90% chance to cut an extra log",metal:"#77602c",edge:"#e1c55d",handle:"#4c3124",shape:3},
  {id:"tallowmere-relic",name:"Tallowmere Relic",slot:"weapon",kind:"axe",category:"weapons",skill:"woodcutting",requiredLevel:99,value:500000,bonusChance:.98,description:"98% chance to cut an extra log",metal:"#6b4934",edge:"#f0d883",handle:"#30271f",shape:4},
];
